/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MetaUpload { 
    id?: number;
    serviceName?: string;
    uploadedDateTime?: string;
    uploadedBy?: string;
    status?: number;
    executeOn?: string;
    approvedBy?: string;
    approvedOn?: string;
    tableName?: string;
    walletId?: number;
    refNo?: string;
}

