/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AmountLimit { 
    id?: number;
    name: string;
    perTxnLimit?: number;
    perDayLimit?: number;
    perMonthLimit?: number;
    currency: string;
    active?: boolean;
    createdOn?: string;
    modifiedOn?: string;
}

