/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MiRole } from './miRole';
import { RoleManagement } from './roleManagement';
import { WalletAccount } from './walletAccount';


export interface CorpUser { 
    id?: number;
    email?: string;
    firstName?: string;
    lastName?: string;
    phone?: string;
    userType?: CorpUser.UserTypeEnum;
    userCategoryType?: CorpUser.UserCategoryTypeEnum;
    active?: boolean;
    role?: MiRole;
    roleData?: RoleManagement;
    username?: string;
    password?: string;
    gender?: CorpUser.GenderEnum;
    accountKycLevel?: CorpUser.AccountKycLevelEnum;
    accountType?: CorpUser.AccountTypeEnum;
    walletAccount?: WalletAccount;
}
export namespace CorpUser {
    export type UserTypeEnum = 'CUSTOMER' | 'AGENT' | 'CORPORATE' | 'BO' | 'USER_CORPORATE';
    export const UserTypeEnum = {
        Customer: 'CUSTOMER' as UserTypeEnum,
        Agent: 'AGENT' as UserTypeEnum,
        Corporate: 'CORPORATE' as UserTypeEnum,
        Bo: 'BO' as UserTypeEnum,
        UserCorporate: 'USER_CORPORATE' as UserTypeEnum
    };
    export type UserCategoryTypeEnum = 'MAKER' | 'CHECKER';
    export const UserCategoryTypeEnum = {
        Maker: 'MAKER' as UserCategoryTypeEnum,
        Checker: 'CHECKER' as UserCategoryTypeEnum
    };
    export type GenderEnum = 'MALE' | 'FEMALE' | 'OTHERS' | 'DEFAULT';
    export const GenderEnum = {
        Male: 'MALE' as GenderEnum,
        Female: 'FEMALE' as GenderEnum,
        Others: 'OTHERS' as GenderEnum,
        Default: 'DEFAULT' as GenderEnum
    };
    export type AccountKycLevelEnum = 'NONE' | 'BASIC' | 'FULL';
    export const AccountKycLevelEnum = {
        None: 'NONE' as AccountKycLevelEnum,
        Basic: 'BASIC' as AccountKycLevelEnum,
        Full: 'FULL' as AccountKycLevelEnum
    };
    export type AccountTypeEnum = 'AGENT' | 'USSD_AGENT' | 'MM_STAFF' | 'MICRO_MERCHANT' | 'MERCHANT';
    export const AccountTypeEnum = {
        Agent: 'AGENT' as AccountTypeEnum,
        UssdAgent: 'USSD_AGENT' as AccountTypeEnum,
        MmStaff: 'MM_STAFF' as AccountTypeEnum,
        MicroMerchant: 'MICRO_MERCHANT' as AccountTypeEnum,
        Merchant: 'MERCHANT' as AccountTypeEnum
    };
}


