/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubAgentCommission } from './subAgentCommission';
import { SlabWiseFeesOrCommission } from './slabWiseFeesOrCommission';
import { MerchantCommission } from './merchantCommission';


export interface FeesOrCommission { 
    id?: number;
    type: FeesOrCommission.TypeEnum;
    active?: boolean;
    amount?: number;
    currency: string;
    slabWiseCommissions?: Array<SlabWiseFeesOrCommission>;
    name?: string;
    commissionCategory?: FeesOrCommission.CommissionCategoryEnum;
    subAgentCommission?: SubAgentCommission;
    merchantCommission?: MerchantCommission;
}
export namespace FeesOrCommission {
    export type TypeEnum = 'FIXED' | 'PERCENT' | 'SLAB_WISE_FIXED' | 'SLAB_WISE_PERCENTAGE';
    export const TypeEnum = {
        Fixed: 'FIXED' as TypeEnum,
        Percent: 'PERCENT' as TypeEnum,
        SlabWiseFixed: 'SLAB_WISE_FIXED' as TypeEnum,
        SlabWisePercentage: 'SLAB_WISE_PERCENTAGE' as TypeEnum
    };
    export type CommissionCategoryEnum = 'CASH_BACK' | 'TAX' | 'FEES' | 'CHARGE' | 'AFC';
    export const CommissionCategoryEnum = {
        CashBack: 'CASH_BACK' as CommissionCategoryEnum,
        Tax: 'TAX' as CommissionCategoryEnum,
        Fees: 'FEES' as CommissionCategoryEnum,
        Charge: 'CHARGE' as CommissionCategoryEnum,
        Afc: 'AFC' as CommissionCategoryEnum
    };
}


