/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductByService } from './productByService';
import { FeesOrCommission } from './feesOrCommission';


export interface MainProduct { 
    id?: number;
    agencyFeesOrCommission?: FeesOrCommission;
    productByService?: ProductByService;
    masterProductId?: number;
    subProductId?: number;
    afacGlAccounts?: string;
}

