/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MainProduct } from './mainProduct';
import { SubProduct } from './subProduct';


export interface MasterProduct { 
    id?: number;
    productName: string;
    description?: string;
    agentCommission?: number;
    ptSubProduct?: SubProduct;
    fwSubProduct?: SubProduct;
    ptAgentMainProductList?: Array<MainProduct>;
    fwAgentMainProductList?: Array<MainProduct>;
    userType: MasterProduct.UserTypeEnum;
    _default?: boolean;
}
export namespace MasterProduct {
    export type UserTypeEnum = 'CUSTOMER' | 'AGENT' | 'CORPORATE' | 'BO' | 'USER_CORPORATE';
    export const UserTypeEnum = {
        Customer: 'CUSTOMER' as UserTypeEnum,
        Agent: 'AGENT' as UserTypeEnum,
        Corporate: 'CORPORATE' as UserTypeEnum,
        Bo: 'BO' as UserTypeEnum,
        UserCorporate: 'USER_CORPORATE' as UserTypeEnum
    };
}


