/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeesOrCommission } from './feesOrCommission';
import { TransactionLimit } from './transactionLimit';
import { Service } from './service';
import { AmountLimit } from './amountLimit';


export interface ProductByService { 
    id?: number;
    ptService?: Service;
    feesOrCommission?: FeesOrCommission;
    feesGlAccountNo?: string;
    chargesAndCommission?: FeesOrCommission;
    chargesGlAccountNo?: string;
    transactionLimit?: TransactionLimit;
    ptTaxComponent?: FeesOrCommission;
    taxGlAccountNo?: string;
    amountLimit?: AmountLimit;
    cashback?: FeesOrCommission;
    cashBackGlAccountNo?: string;
}

