/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeesOrCommission } from './feesOrCommission';


export interface SlabWiseFeesOrCommission { 
    id?: number;
    type: SlabWiseFeesOrCommission.TypeEnum;
    minAmount?: number;
    name?: string;
    maxAmount?: number;
    active?: boolean;
    amount?: number;
    feesOrCommission?: FeesOrCommission;
}
export namespace SlabWiseFeesOrCommission {
    export type TypeEnum = 'SLAB_WISE_FIXED' | 'SLAB_WISE_PERCENTAGE';
    export const TypeEnum = {
        Fixed: 'SLAB_WISE_FIXED' as TypeEnum,
        Percentage: 'SLAB_WISE_PERCENTAGE' as TypeEnum
    };
}


