/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductByService } from './productByService';


export interface SubProduct { 
    id?: number;
    name?: string;
    subProdType?: SubProduct.SubProdTypeEnum;
    combo?: Array<ProductByService>;
}
export namespace SubProduct {
    export type SubProdTypeEnum = 'PT' | 'FPW';
    export const SubProdTypeEnum = {
        Pt: 'PT' as SubProdTypeEnum,
        Fpw: 'FPW' as SubProdTypeEnum
    };
}


