/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WalletAccount { 
    id?: number;
    accountNo?: string;
    accountDescription?: string;
    subAccountNo?: string;
    headAccountNo?: string;
    type?: WalletAccount.TypeEnum;
    walletType?: string;
    productReference?: number;
    branchCode: string;
    acDesc?: string;
    cifNo?: string;
    ccy?: string;
    baseUserId?: number;
    acOpenDate?: string;
    acStmtDay?: string;
    makerId?: number;
    makerDtStamp?: string;
    checkerId?: number;
    checkerDtStamp?: string;
    accRemarks?: string;
    walletStatus?: WalletAccount.WalletStatusEnum;
    walletNo?: string;
    wallet?: boolean;
}
export namespace WalletAccount {
    export type TypeEnum = 'ASSET' | 'LIABILITY' | 'INCOME' | 'EXPENSE';
    export const TypeEnum = {
        Asset: 'ASSET' as TypeEnum,
        Liability: 'LIABILITY' as TypeEnum,
        Income: 'INCOME' as TypeEnum,
        Expense: 'EXPENSE' as TypeEnum
    };
    export type WalletStatusEnum = 'NO_CREDIT' | 'NO_DEBIT' | 'LOCKED' | 'NO_LOCK' | 'OK' | 'DORMANT' | 'AUTHORIZED' | 'UNAUTHORIZED';
    export const WalletStatusEnum = {
        NoCredit: 'NO_CREDIT' as WalletStatusEnum,
        NoDebit: 'NO_DEBIT' as WalletStatusEnum,
        Locked: 'LOCKED' as WalletStatusEnum,
        NoLock: 'NO_LOCK' as WalletStatusEnum,
        Ok: 'OK' as WalletStatusEnum,
        Dormant: 'DORMANT' as WalletStatusEnum,
        Authorized: 'AUTHORIZED' as WalletStatusEnum,
        Unauthorized: 'UNAUTHORIZED' as WalletStatusEnum
    };
}


